---
- name: Copy dockerhub server_files
  copy:
    src: "dockerhub/"
    dest: "/home/{{ dockerhub_user }}/dockerhub"
    mode: "0755"
    owner: "{{ dockerhub_user }}"
    group: "{{ dockerhub_user }}"

- name: Copy docker-compose.yml
  template:
    src: 'docker-compose.yml.j2'
    dest: '/home/{{ dockerhub_user }}/dockerhub/docker-compose.yml'
    owner: "{{ dockerhub_user }}"
    group: "{{ dockerhub_user }}"
    mode: '0755'
  ignore_errors: true

- name: Start DockerHub container
  command: "{{ docker_compose_path }} -f /home/{{ dockerhub_user }}/dockerhub/docker-compose.yml up -d"
  become: yes
  become_user: "{{ dockerhub_user }}"
  ignore_errors: true

