---
- name: Copy SSL CRT certificate hosts
  copy:
    src: "{{ item.vname }}.crt"
    dest: "/etc/ssl/{{ item.vname }}.crt"
    mode: "0664"
    owner: "root"
    group: "root"
  with_items: "{{ vhosts }}"
  when: (vhosts is defined)

- name: Copy SSL KEY certificate hosts
  copy:
    src: "{{ item.vname }}.key"
    dest: "/etc/ssl/{{ item.vname }}.key"
    mode: "0664"
    owner: "root"
    group: "root"
  with_items: "{{ vhosts }}"
  when: (vhosts is defined)

- name: Install Nginx config {{ item.vname }}
  become: true
  template:
    src: templates/vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.vname }}.conf"
    force: yes
    owner: root
    group: root
    mode: '644'
  with_items: "{{ vhosts }}"
  when: (vhosts is defined)

- name: Reload nginx to activate site
  service: 
    name: nginx 
    state: restarted

    